version: 2
updates:
  # Go
  - package-ecosystem: "gomod"
    # checks /go.mod
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      go-modules:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
